# Generated by Django 3.2.5 on 2022-05-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0002_rename_users_adminusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUsers',
            new_name='UserAuthentication',
        ),
    ]
